[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@6.6.0
    ropg/LoRaWAN_ESP32@1.1.0
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.4.0
